version: "3.8"

services:
  teams-bot-prod:
    build:
      context: .
      target: production
    ports:
      - "3978:3978"
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env.production:/usr/src/app/.env.production:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
